export const POSE_CONNECTIONS = [
  [11, 12],
  [11, 13],
  [13, 15],
  [12, 14],
  [14, 16],
  [11, 23],
  [12, 24],
  [23, 24],
  [23, 25],
  [25, 27],
  [24, 26],
  [26, 28],
] as const;

export const POSE_LANDMARK_IDS = [
  'nose',
  'left-eye-inner',
  'left-eye',
  'left-eye-outer',
  'right-eye-inner',
  'right-eye',
  'right-eye-outer',
  'left-ear',
  'right-ear',
  'mouth-left',
  'mouth-right',
  'left-shoulder',
  'right-shoulder',
  'left-elbow',
  'right-elbow',
  'left-wrist',
  'right-wrist',
  'left-pinky',
  'right-pinky',
  'left-index',
  'right-index',
  'left-thumb',
  'right-thumb',
  'left-hip',
  'right-hip',
  'left-knee',
  'right-knee',
  'left-ankle',
  'right-ankle',
  'left-heel',
  'right-heel',
  'left-foot-index',
  'right-foot-index',
] as const;
